groups:
- name: fila acumulando
  rules:
  - alert: FilaAcumulando
    expr: rabbitmq_queue_messages_ready{queue!~".*(deadletter|limbo).*"} != 0 and increase(rabbitmq_queue_messages_ready{queue!~".*(deadletter|limbo).*"}[30s]) > 0
      #Expr. de teste rapido - expr: rate(rabbitmq_queue_messages_ready{queue!~".*(deadletter|limbo).*"}[500m]) > rate(rabbitmq_queue_messages_unacknowledged{queue!~".*(deadletter|limbo).*"}[500m])
    for: 2m
    labels:
      severity: critical
      
    annotations:
      summary: 'Fila acumulando'
      description: 'A fila está acumulando mensagens de maneira anormal'
        #text: 'Há mensagens paradas na fila. A taxa de mensagens prontas é maior do que a taxa de mensagens não confirmadas.'
