global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['IP:9419']
        #metrics_path: /metrics
    params:
      exclude_metrics: ['rabbitmq_queue_reductions_total']
        
rule_files:
  - 'alert.rules.yml'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['10.50.1.53:9093']
